Neyanbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tinymce/", include('tinymce.urls')),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('login/complete/', views.login_complete_view, name='login-complete'),
    path('register/', views.register_view, name='register'),
    path('register/complete/', views.register_complete_view, name='register-complete'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/edit/', views.edit_profile_view, name='profile-edit'),
    path('dashboard/compare/', views.compare_list_view, name='compare-list'),
    path('dashboard/compare/action/', views.compare_list_handler, name='compare-handler'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('view_handler/', views.view_handler, name='view_handler'),
    path('comment/', views.comment_view, name='comment_view'),
    path('editor/upload/', views.editor_upload_handler, name='editor-upload'),
    path('posts/list/', views.post_list_view, name='post-list'),
    path('posts/detail/<slug>/', views.post_detail_view, name='post-detail'),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('credit-card/', views.credit_card_view, name='credit_card'),
    path('credit-card/create/', views.credit_card_create_view, name='credit_card_create'),
    path('credit-card/charge/<charge>/', views.credit_card_charge_view, name='credit_card_charge'),
    path('request/perfume/', views.perfume_request_view, name='perfume-request'),
    path('about-us/', views.about_us_view, name='about_us'),
    path('terms/', views.terms_view, name='terms'),
    # path('faq/', views.faq_view, name='faq'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from random import choice
import os


class UserManager(BaseUserManager):

    def create_user(self, phone, password=None, **extra_fields):
        if not phone:
            raise ValueError('Users must have a phone number')
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(phone, password, **extra_fields)


def profile_directory_path(instance, filename):
    return os.path.join(
        'Profiles',
        f'user_{instance.id}',
        filename
    )

class User(AbstractBaseUser, PermissionsMixin):
    phone = models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')
    email = models.EmailField(max_length=255, blank=True, null=True, verbose_name='ایمیل')
    name = models.CharField(max_length=60, verbose_name='نام')
    profile = models.ImageField(upload_to=profile_directory_path, default=choice(['Profiles/default-1.webp', 'Profiles/default-2۰۹۴۵۸۷۳۸۵۳۴.webp']),verbose_name='پروفایل', help_text='60*60')

    compare_list = models.ManyToManyField('shop.Product', related_name='users_compare_list', blank=True, verbose_name='لیست مقایسه')

    is_active = models.BooleanField(default=True, verbose_name='دسترسی به حساب')
    is_staff = models.BooleanField(default=False, verbose_name='کارمند سایت')
    is_superuser = models.BooleanField(default=False, verbose_name='صاحب سایت')

    date_joined = models.DateTimeField(default=timezone.now, verbose_name='تاریخ ایجاد حساب')

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'

shop/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Min
from django.urls import reverse
from django.utils.text import slugify
from tinymce.models import HTMLField
from account.models import User
from main.utilities import send_sms, PRODUCT_NOTIFY_ME
import re
import os


def product_dynamic_path(instance, filename):
    return os.path.join(
        'Products',
        'content',
        filename
    )

def video_validator(value):
    format = os.path.splitext(value.name)[1]
    if format.lower() != '.mp4':
        raise ValidationError('فقط فایل های ویدیویی mp4 قابل قبول می باشد!')


class Product(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=100, verbose_name='اسم محصول', help_text='به فارسی')
    name_en = models.CharField(max_length=100, verbose_name='اسم محصول', help_text='به انگلیسی')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')

    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, related_name='products', blank=True, null=True, verbose_name='برند')
    available_volumes = models.ManyToManyField('Volume', related_name='products', blank=True, verbose_name='حجم های موجود')

    smell = models.ManyToManyField('ProductSmell', verbose_name='گروه بویایی')

    class SpreadChoices(models.TextChoices):
        LOW = 'LOW', 'ضعیف'
        MEDIUM = 'MEDIUM', 'متوسط'
        HIGH = 'HIGH', 'قوی'
    spread = models.CharField(choices=SpreadChoices.choices, max_length=6, verbose_name='پخش بو')

    class SeasonChoices(models.TextChoices):
        WINTER = 'WINTER', 'پاییز - زمستان'
        SUMMER = 'SUMMER', 'بهار - تابستان'
        ALL_SEASONS = 'ALL_SEASONS', 'چهار فصل'
    season = models.CharField(choices=SeasonChoices.choices, max_length=12, verbose_name='فصل')

    class TasteChoices(models.TextChoices):
        SPICY = 'SPICY', 'تند'
        SWEET = 'SWEET', 'شیرین'
        BITTER = 'BITTER', 'تلخ'
        SOUR = 'SOUR', 'ترش'
    taste = models.CharField(choices=TasteChoices.choices, max_length=6, verbose_name='طعم')

    class NatureChoices(models.TextChoices):
        WARM = 'WARM', 'گرم'
        COLD = 'COLD', 'خنک'
    nature = models.CharField(choices=NatureChoices.choices, max_length=4, verbose_name='طبع')

    class DurabilityChoices(models.TextChoices):
        LOW = 'LOW', 'بالا'
        MEDIUM = 'MEDIUM', 'متوسط'
        HIGH = 'HIGH', 'پایین'
    durability = models.CharField(choices=DurabilityChoices.choices, max_length=6, verbose_name='ماندگاری')

    class GenderChoices(models.TextChoices):
        MALE = 'MALE', 'مردانه'
        FEMALE = 'FEMALE', 'زنانه'
        UNISEX = 'UNISEX', 'مشترک'
    gender = models.CharField(choices=GenderChoices.choices, max_length=6, verbose_name='جنسیت')

    class TypeChoices(models.TextChoices):
        PERFUME = 'PERFUME', 'پرفیوم'
        EAU_DE_PARFUM = 'EAU_DE_PARFUM', 'ادوپرفیوم'
        EAU_DE_TOILETTE = 'EAU_DE_TOILETTE', 'ادوتویلت'
        EAU_DE_COLOGNE = 'EAU_DE_COLOGNE', 'ادوکلن'
        BODY_SPLASH = 'BODY_SPLASH', 'بادی اسپلش'
    perfume_type = models.CharField(choices=TypeChoices.choices, max_length=15, verbose_name='نوع')

    pid = models.CharField(max_length=6, unique=True, verbose_name='کد محصول')

    price = models.PositiveIntegerField(default=0, verbose_name='قیمت محصول', help_text='به ازای هر گرم / به تومان')
    discount = models.IntegerField(default=-1, validators=[MinValueValidator(-1)], verbose_name='قیمت پس از تخفیف', help_text='-۱ برای لغو تخفیف')
    reset_discount_at = models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخفیف')

    inventory = models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')

    short_description = HTMLField(verbose_name='توضیحات کوتاه')
    description = HTMLField(verbose_name='توضیحات اصلی')

    video = models.FileField(upload_to=product_dynamic_path, blank=True, null=True, validators=[video_validator], verbose_name='ویدیو توضیحات', help_text='.mp4')

    site_score = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name='امتیاز سایت')

    views = models.PositiveIntegerField(default=0, verbose_name='بازدید ها')
    liked_by = models.ManyToManyField(User, blank=True, related_name='liked_products', verbose_name='کسانی که این محصول را پسندیده اند')
    bought_by = models.ManyToManyField(User, blank=True, related_name='bought_products', verbose_name='کسانی که این محصول را خریده اند')
    remind_to = models.ManyToManyField(User, blank=True, related_name='reminder_products', verbose_name='کسانی که منتظر موجود شدن این محصول هستند')

    is_visible = models.BooleanField(default=False, verbose_name='نمایش در سایت')

    last_view = models.DateTimeField(blank=True, null=True, verbose_name='اخرین بازدید')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')

    def __str__(self):
        return self.name

    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super().from_db(db, field_names, values)
        instance._original_inventory = instance.inventory
        return instance

    def save(self, *args, **kwargs):
        if self.pk:
            if not self._original_inventory and self.inventory:
                for user in self.remind_to.all():
                    send_sms(user.phone, PRODUCT_NOTIFY_ME, user.name, self.name)
                self.remind_to.clear()

        if any(ch.isupper() for ch in self.slug):
            self.slug = self.slug.lower()
        super().save(*args, **kwargs)
        self._original_inventory = self.inventory  # update cached value after save


    def get_raw_price(self):
        return self.price * int(self.available_volumes.aggregate(Min('volume'))['volume__min'] or 1)
    def get_price(self):
        return self.price * int(self.available_volumes.aggregate(Min('volume'))['volume__min'] or 1) if self.discount == -1 else self.discount * int(self.available_volumes.aggregate(Min('volume'))['volume__min'] or 1)

    def get_volume_price(self, volume):
        return self.price * volume if self.discount == -1 else self.discount * volume


    get_price.short_description = 'کمترین قیمت موجود'

    def get_price_difference(self):
        return 100 - int((self.discount / self.price) * 100)

    def get_smell(self):
        return ', '.join([smell.name for smell in self.smell.all()])

    def get_volumes(self):
        return ', '.join(list(volume for volume in self.available_volumes.values_list('name', flat=True)))

    def get_absolute_url(self):
        return reverse('shop:product-detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'
        ordering = ['-created_at']
        indexes = [
            models.Index(
                fields=['-created_at'],
            )
        ]


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images', verbose_name='محصولات')
    image = models.ImageField(upload_to=product_dynamic_path, verbose_name='تصویر', help_text='No Background | .png or .webp')
    alt = models.CharField(verbose_name='تیتر', help_text='برای سئو')

    def __str__(self):
        return f'{self.product.name} | {self.image.name}'

    def delete(self, *args, **kwargs):
        os.remove(self.image.path)
        return super().delete(*args, **kwargs)

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'تصاویر'


class Features(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='features', verbose_name='محصول')
    key = models.CharField(max_length=30, verbose_name='ویزگی')
    value = models.CharField(max_length=100, verbose_name='مقدار')

    def __str__(self):
        return f'{self.product.name} | {self.key}: {self.value}'

    class Meta:
        verbose_name = 'ویژگی'
        verbose_name_plural = 'ویژگی ها'


class ProductSmell(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=50, verbose_name='گروه بویایی')
    icon = models.ImageField(upload_to='Smells/Icons', verbose_name='آیکون', help_text='80*80')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product-list') + f'?smells={self.name}'

    class Meta:
        verbose_name = 'گروه بویایی'
        verbose_name_plural = 'گروه های بویایی'


class Brand(models.Model):
    objects = models.Manager()

    name = models.CharField(verbose_name='نام برند', unique=True, max_length=100)
    logo = models.ImageField(upload_to='Brands/Logo', verbose_name='لوگو', help_text='45*45 | white BG')
    banner = models.ImageField(upload_to='Brands/Banner', verbose_name='بنر', help_text='285*336')
    slug = models.SlugField(verbose_name='اسلاگ', unique=True, max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product-list') + f'?brands={self.slug}'

    def save(self, *args, **kwargs):
        if any(ch.isupper() for ch in self.slug):
            self.slug = self.slug.lower()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'برند'
        verbose_name_plural = 'برند ها'


class Comment(models.Model):
    objects = models.Manager()

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='shop_comments', verbose_name='کاربر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', verbose_name='محصول')

    score = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='امتیاز')
    content = models.TextField(max_length=320, verbose_name='متن')

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
import re


phone_pattern = re.compile(r'^09\d{9}$')
email_pattern = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')


def validate_phone(number):
    return bool(phone_pattern.match(number))


def validate_email(email):
    return bool(email_pattern.match(email))


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('phone', 'name', 'is_active', 'is_staff', 'is_superuser')

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')

        if self.instance.pk:
            if User.objects.filter(phone=phone).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('Phone already exists.')
        else:
            if User.objects.filter(phone=phone).exists():
                raise forms.ValidationError('Phone already exists.')

        if not phone.isdigit():
            raise forms.ValidationError('phone must be a number.')

        if not phone.startswith('09'):
            raise forms.ValidationError('phone must start with 09 digits.')

        if len(phone) != 11:
            raise forms.ValidationError('phone must have 11 digits.')

        return phone


class UserChangeFormNew(UserChangeForm):
    class Meta:
        model = User
        fields = ('phone', 'name', 'is_active', 'is_staff', 'is_superuser')

account/templates/compare.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}

{% block title %}
	مقایسه محصولات
{% endblock %}

{% block title_og %}
	مقایسه محصولات
{% endblock %}

{% block page_keywords %}
    لیست مقایسه, مقایسه محصولات, مقایسه عطرها, محصولات ذخیره شده, مقایسه ادکلن, خرید عطر, افزودن به سبد خرید, فروشگاه نی عنبر, عطرهای محبوب, انتخاب عطر, خرید آسان عطر,
{% endblock %}

{% block page_description %}
    در صفحه لیست مقایسه نی عنبر، محصولات ذخیره شده خود را به راحتی مقایسه کنید و بهترین عطر را انتخاب نمایید. با امکان افزودن سریع به سبد خرید، تجربه خریدی آسان و مطمئن را داشته باشید.
{% endblock %}

{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">لیست مقایسه ها</h1>
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}"><i class="fa-light fa-house"></i></a></li>
                    <li>لیست مقایسه ها</li>
                </ul>
            </div>
        </nav>
        <div class="page-content compare-default compare-page">
            <div class="container themeparsi-compare-table">
                <div class="compare-row compare-basic">
                    <div class="compare-col compare-field">
                        محصولات
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" id="title-{{ product.id }}" data-title="{{ product }}">
                            <div class="product product-classic text-center">
                                <figure class="product-media">
                                    <a class="link-{{ product.id }}" href="{{ product.get_absolute_url }}">
                                        <picture>
                                            <source id="image-{{ product.id }}" srcset="{{ product.images.first.image.url }}" type="image/webp">
                                            <img loading="lazy" decoding="async" src="{{ product.images.first.image.url }}" alt="product" width="280" height="315">
                                        </picture>
                                    </a>
                                    {% if product.discount != -1 %}
                                        <div class="product-label-group">
                                            <label class="product-label label-sale">%{{ product.get_price_difference }} تخفیف</label>
                                        </div>
                                    {% endif %}
                                </figure>
                                <div class="product-details rtl">
                                    <div class="product-action">
                                        <a href="#" class="btn-product-icon btn-default add-to-cart" data-id="{{ product.id }}" title="اضافه به سبد"
                                           data-toggle="modal" data-target="#addCartModal">
                                            <i class="fa-light fa-cart-shopping"></i>
                                        </a>
                                        <a href="#" class="btn-product-icon btn-default btn-add-wishlist" data-id="{{ product.id }}"
                                           title="اضافه به علاقه مندی"><i class="fa-light fa-heart" id="like-icon-{{ product.id }}" {% if request.user in product.liked_by.all %}style="color: red;"{% endif %}></i></a>
                                        <a href="#" class="btn-product-icon btn-default btn-remove-product" data-id="{{ product.id }}" title="Add to close">
                                            <i class="fa-light fa-xmark"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-title rtl text-right delete-{{ product.id }}">
                    <div class="compare-col compare-field">
                        عنوان
                    </div>
                        {% for product in compare_list %}
                            <div class="compare-col compare-value delete-{{ product.id }}" data-title="Title">
                                <a href="{{ product.get_absolute_url }}">{{ product }}</a>
                            </div>
                        {% endfor %}
                    </div>
                <div class="compare-row compare-sku rtl text-right">
                    <div class="compare-col compare-field">
                        برند
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Sku">
                            {{ product.brand }}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-pa_brands rtl text-right">
                    <div class="compare-col compare-field">
                        قیمت
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Brands">
                            {{ product.get_price | commafy }} تومان
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-pa_color  rtl text-right">
                    <div class="compare-col compare-field">
                        ماندگاری
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Color">
                            {{ product.get_durability_display }}
                        </div>
                    {% endfor %}

                </div>
                <div class="compare-row compare-type rtl text-right">
                    <div class="compare-col compare-field">
                        سایز
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Type">
                            {{ product.get_volumes }}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-availability rtl text-right">
                    <div class="compare-col compare-field">
                        دسترسی
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Availability">
                            <p class="stock in-stock">{% if product.inventory %}{{ product.inventory }} موجودی{% else %}اتمام موجودی{% endif %}</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-description rtl text-right">
                    <div class="compare-col compare-field">
                        ویژگی:
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="توضیحات">
                            {% for feature in product.features.all %}
                                {{ feature.key }}:{{ feature.value }} {% if not forloop.last %} - {% endif %}
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-rating rtl text-right">
                    <div class="compare-col compare-field">
                        فصل
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Ratings & Reveiews">
                            <div class="ratings-container">
                               {{ product.get_season_display }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-sku rtl text-right">
                    <div class="compare-col compare-field">
                        طعم
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Sku">
                            {{ product.get_taste_display }}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-pa_brands rtl text-right">
                    <div class="compare-col compare-field">
                        طبع
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Brands">
                            {{ product.get_nature_display }}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-pa_color  rtl text-right">
                    <div class="compare-col compare-field">
                        گروه بویایی
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Color">
                            {{ product.get_smell }}
                        </div>
                    {% endfor %}
                </div>
                <div class="compare-row compare-pa_size  rtl text-right">
                    <div class="compare-col compare-field">
                        جنسیت
                    </div>
                    {% for product in compare_list %}
                        <div class="compare-col compare-value delete-{{ product.id }}" data-title="Size">
                            {{ product.get_gender_display }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block script %}
    <script defer src="{% static 'js/compare.js' %}"></script>
{% endblock %}