Neyanbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tinymce/", include('tinymce.urls')),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('view_handler/', views.view_handler, name='view_handler'),
    path('comment/', views.comment_view, name='comment_view'),
    path('editor/upload/', views.editor_upload_handler, name='editor-upload'),
    path('posts/list/', views.post_list_view, name='post-list'),
    path('posts/detail/<slug>/', views.post_detail_view, name='post-detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('list/', views.cart_view, name='cart'),
    path('add/', views.add_view, name='add'),
    path('update/', views.update_view, name='update'),
    path('delete/', views.delete_view, name='delete'),
    path('discount/', views.apply_discount, name='apply_discount'),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('credit-card/', views.credit_card_view, name='credit_card'),
    path('credit-card/create/', views.credit_card_create_view, name='credit_card_create'),
    path('credit-card/charge/<charge>/', views.credit_card_charge_view, name='credit_card_charge'),
    path('request/perfume/', views.perfume_request_view, name='perfume-request'),
    path('about-us/', views.about_us_view, name='about_us'),
    path('terms/', views.terms_view, name='terms'),
    # path('faq/', views.faq_view, name='faq'),
]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('', views.order_view, name='order'),
    path('submit/', views.order_submit, name='order_submit'),
    path('submit/verify/', views.verify_order, name='verify_order'),
    path('status/<order_id>/', views.order_status, name='order_status'),
    path('pay/', views.pay_order, name='pay-order'),
    path('zarinpal/request/', views.zarinpal_request, name='zarinpal_request'),
    path('zarinpal/verify/', views.zarinpal_verify, name='zarinpal_verify'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('view_handler/', views.view_handler, name='view_handler'),
    path('like_handler/', views.like_handler, name='like_handler'),
    path('comment_handler/', views.comment_handler, name='comment_handler'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('notify_me/', views.notify_me, name='notify_me'),
    path('products/list/', views.product_list_view, name='product-list'),
    path('products/detail/<slug>/', views.product_view, name='product-detail'),
]

order/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.template.context_processors import request
from zeep.exceptions import ValidationError

from shop.models import Product, Volume
from main.models import Setting
from account.models import User
from django.utils import timezone


class Order(models.Model):
    objects = models.Manager()

    class ReceiveChoices(models.TextChoices):
        POST = 'POST', 'به صورت پستی'
        IN_PERSON = 'IN_PERSON', 'به صورت حضوری'

    class StatusChoices(models.TextChoices):
        NOT_PAID = 'NOT_PAID', 'پرداخت نشده'
        PENDING = 'PENDING', 'در انتظار تایید'
        CONFIRMED = 'CONFIRMED', 'تایید شد'
        IN_PROGRESS = 'IN_PROGRESS', 'در حال آماده سازی'
        READY_TO_SHIP = 'READY_TO_SHIP', 'آماده تحویل'
        SHIPPED = 'SHIPPED', 'تحویل داده شد'
        FINISHED = 'FINISHED', 'تکمیل شد'
        REJECTED = 'REJECTED', 'لغو شد'

    order_id = models.CharField(max_length=12, unique=True, verbose_name='کد سفارش')
    user = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='کاربر')
    name = models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')
    phone = models.CharField(max_length=11, verbose_name='شماره تلفن')
    national_code = models.CharField(max_length=10, verbose_name='کد ملی')
    email = models.EmailField(max_length=255, blank=True, null=True, verbose_name='ایمیل')
    province = models.CharField(max_length=30, blank=True, verbose_name='استان')
    city = models.CharField(max_length=30, blank=True, verbose_name='شهر')
    address = models.CharField(max_length=300, blank=True, verbose_name='آدرس')
    postal_code = models.CharField(max_length=10, blank=True, verbose_name='کد پستی')
    not_for_me = models.BooleanField(default=False, verbose_name='سفارش برای شخص دیگری است')
    receive_type = models.CharField(max_length=13, choices=ReceiveChoices.choices, default=ReceiveChoices.POST, verbose_name='نوع دریافت')
    receive_time = models.DateField(blank=True, null=True, verbose_name='زمان دریافت')
    status = models.CharField(max_length=17, choices=StatusChoices.choices, default=StatusChoices.NOT_PAID, verbose_name='وضعیت')
    description = models.TextField(max_length=500, blank=True, verbose_name='توضیحات سفارش')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')

    def __str__(self):
        return f'{self.order_id}سفارش '

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.user and self.items.exists():
            for item in self.items.all():
                if self.user not in item.product.bought_by.all():
                    item.product.bought_by.add(self.user)


    def get_total_cost(self):
        settings = Setting.objects.first()
        total = sum(item.price for item in self.items.all())
        return int(total * (1 + settings.tax_fee / 100) + settings.get_post_fee(total))

    def get_parcel_items(self):
        return [{'description': item.product.name, 'product_id': item.product.id,
                 'properties': {'حجم': item.volume.name, 'pid': item.product.pid}, 'quantity': item.quantity,
                 'price': item.price * 10} for item in self.items.all()]

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'


class OrderItem(models.Model):
    objects = models.Manager()
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='سفارش')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, related_name='order_items', verbose_name='حجم')
    quantity = models.PositiveIntegerField(verbose_name='تعداد')
    price = models.PositiveIntegerField(default=0, verbose_name='هزینه', help_text='با در نظر گرفتن حجم و تعداد')

    def calculate_price(self, request):
        if request.session.get('discount'):
            discount = Discount.objects.get(id=request.session.get('discount'))
            if discount.is_valid():
                return discount.get_price(self.product, self.volume) * self.quantity
        return self.product.get_volume_price(self.volume.volume) * self.quantity

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)


class Discount(models.Model):
    objects = models.Manager()
    token = models.CharField(max_length=10, verbose_name='کد تخقیف')
    value = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(100)],
                                        verbose_name='تخفیف به درصد')
    selected = models.CharField(default='', verbose_name='محصولات و کاربران انتخاب شده',
                                help_text='products:<<slug1;slug2;...> or all>|p_exclude:<slug1;slug2;...>|users:<id1;id2;...> or all|u_exclude:<id1;id2;...>')
    users = models.ManyToManyField(User, related_name='used_discounts', blank=True,
                                   verbose_name='کسانی که از این تخفیف استفاده کرده اند')
    expire_at = models.DateField(verbose_name='زمان انقضا')

    def is_expired(self):
        if timezone.now().date().today() > self.expire_at:
            return True
        return False

    def get_list(self, obj: str):
        return obj.split(':')[1].split(';')

    def get_selected_users(self):
        # users:<id1;id2;...> or all|u_exclude:<id1;id2;...>
        if not self.selected:
            return []
        selected_users = self.selected.split('|')[2:]
        users, excluded_users = selected_users[0], selected_users[1]
        return User.objects.all().exclude(id__in=self.get_list(excluded_users)) if users.split(':')[
                                                                                       1] == 'all' else User.objects.filter(
            id__in=self.get_list(users)).exclude(id__in=self.get_list(excluded_users))

    def is_valid(self, user) -> tuple[bool, str | Product]:
        if self.is_expired():
            return False, 'زمان این تخفیف به پایان رسیده است'

        if user in self.users.all():
            return False, 'شما قبلا از تخفیف استفاده کرده اید'

        if user not in self.get_selected_users():
            return False, 'این تخفیف شامل شما نمی شود'

        selected_products = self.selected.split('|')[:2]
        products, excluded_products = selected_products[0], selected_products[1]
        if products.split(':')[1] == 'all':
            return True, Product.objects.all().exclude(slug__in=self.get_list(excluded_products))
        return True, Product.objects.filter(slug__in=self.get_list(products)).exclude(slug__in=self.get_list(excluded_products))

    def get_price(self, product: Product, volume):
        # products:<<slug1;slug2;...> or all>|p_exclude:<slug1;slug2;...
        selected_products = self.selected.split('|')[:2]
        products, excluded_products = selected_products[0], selected_products[1]
        all_products = None
        if products.split(':')[1] == 'all':
            all_products = Product.objects.all().exclude(slug__in=self.get_list(excluded_products))
        else:
            all_products = Product.objects.filter(slug__in=self.get_list(products)).exclude(
                slug__in=self.get_list(excluded_products))
        discount = 1 - (self.value / 100)
        return int(
            product.get_volume_price(volume) * discount if product in all_products else product.get_volume_price(
                volume))

    class Meta:
        verbose_name = 'تخفیف'
        verbose_name_plural = 'تخفیف ها'


class CreditCart(models.Model):
    objects = models.Manager()
    token = models.CharField(max_length=10, verbose_name='توکن کارت')
    credit = models.PositiveIntegerField(verbose_name='اعتبار کارت')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='credit_cart', verbose_name='ساخته شده توسط')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')

    def buy(self, price):
        if self.credit >= price:
            self.credit -= price
            self.save()
            return True
        return False

    def __str__(self):
        return f' {self.token}کارت هدیه:'

    class Meta:
        verbose_name = 'کارت هدیه'
        verbose_name_plural = 'کارت های هدیه'


class Transaction(models.Model):
    objects = models.Manager()

    class PaymentChoices(models.TextChoices):
        GATEWAY = 'GATEWAY', 'از طریق درگاه پرداخت'
        CREDIT = 'CREDIT', 'با کارت اعتباری'

    order = models.ForeignKey(Order, on_delete=models.SET_NULL, related_name='transactions', null=True, verbose_name='برای سفارش')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='توسط')
    payment_type = models.CharField(max_length=21, choices=PaymentChoices.choices, verbose_name='نوع پرداخت')
    paid_amount = models.IntegerField(verbose_name='هزینه دریافتی')
    content = models.TextField(verbose_name='توضیحات', blank=True)

    def __str__(self):
        return f'{self.order} - {self.user}'

    class Meta:
        verbose_name = 'تراکنش'
        verbose_name_plural = 'تراکنش ها'

order/templates/order-status.html
{% extends 'base.html' %}
{% load tags %}
{% load static %}

{% block title %}
	وضعیت سفارش
{% endblock %}

{% block page_description %}
    وضعیت سفارش شما در فروشگاه نی عنبر. آخرین اطلاعات مربوط به سفارش و ارسال را مشاهده کنید.
{% endblock %}

{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">وضعیت سفارش</h1>
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}"><i class="fa-light fa-house"></i></a></li>
                    <li>وضعیت سفارش</li>
                </ul>
            </div>
        </nav>
        <div class="page-content  order">
            <div class="container">
                <div class="order-message mr-auto ml-auto">
                    <div class="icon-box d-inline-flex align-items-center">
                        <div class="icon-box-icon mb-0">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 50 50"
                                 enable-background="new 0 0 50 50" xml:space="preserve">
								<g>
								<path fill="none" stroke-width="3" stroke-linecap="round"
                                      stroke-linejoin="bevel" stroke-miterlimit="10" d="
											M33.3,3.9c-2.7-1.1-5.6-1.8-8.7-1.8c-12.3,0-22.4,10-22.4,22.4c0,12.3,10,22.4,22.4,22.4c12.3,0,22.4-10,22.4-22.4
											c0-0.7,0-1.4-0.1-2.1"></path>
                                    <polyline fill="none" stroke-width="4" stroke-linecap="round"
                                              stroke-linejoin="bevel" stroke-miterlimit="10" points="
											48,6.9 24.4,29.8 17.2,22.3 	"></polyline>
									</g>
								</svg>
                        </div>
                        <div class="icon-box-content text-right">
                            <h5 class="icon-box-title font-weight-bold">
                                {% if messages %}
                                    {% for message in messages %}
                                    	{{ message }}
                                    {% endfor %}
                                {% else %}
                                    {% if order.status == 'NOT_PAID' %}
                                        در انتظار پرداخت
                                    {% elif order.status == 'REJECTED' %}
                                        سفارش شما لغو شده است
                                    {% else %}
                                        متشکریم از خرید شما!
                                    {% endif %}
                                {% endif %}
                            </h5>
                            <p class="lh-1 ls-m">اطلاعات سفارش: {{ order.order_id }}</p>
                        </div>
                    </div>
                </div>
                <div class="order-results">
                    <div class="overview-item">
                        <span>کد سفارش:</span>
                        <strong id="order_id">{{ order.order_id }}</strong>
                    </div>
                    <div class="overview-item">
                        <span>وضعیت:</span>
                        <strong>{{ order.get_status_display }}</strong>
                    </div>
                    <div class="overview-item">
                        <span> تحویل  :</span>
                        <strong>{{ order.receive_time | to_jalali_verbose }}</strong>
                    </div>
                    <div class="overview-item">
                        <span>شماره تلفن:</span>
                        <strong>{{ order.phone }}</strong>
                    </div>
                    <div class="overview-item">
                        <span>کد پستی:</span>
                        <strong>{{ order.postal_code }}</strong>
                    </div>
                    <div class="overview-item">
                        <span> جمع:</span>
                        <strong> {{ order.get_total_cost | commafy }} تومان </strong>
                    </div>
                </div>
                <h2 class="title title-simple text-right pt-4 font-weight-bold">جزئیات فاکتور</h2>
                <div class="order-details">
                    <table class="order-details-table">
                        <thead>
                        <tr class="summary-subtotal">
                            <td>
                                <h3 class="summary-subtitle">محصول</h3>
                            </td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in order.items.all %}
                            <tr>
                                <td class="product-name">
                                    {{ item.product }}<span>
											<i class="fa-light fa-times"></i>
											{{ item.quantity }}
										</span>
                                </td>
                                <td class="product-price"> {{ item.price | commafy }} تومان </td>
                            </tr>
                        {% endfor %}
                        <tr class="summary-subtotal">
                            <td>
                                <h4 class="summary-subtitle">جمع محصولات:</h4>
                            </td>
                            <td class="summary-subtotal-price"> {{ total_before_tax | commafy }} تومان </td>
                        </tr>
                        <tr class="summary-subtotal">
                            <td>
                                <h4 class="summary-subtitle">روش پرداخت:</h4>
                            </td>
                            <td class="summary-subtotal-price">{{ order.transactions.first.get_payment_type_display }}</td>
                        </tr>
                        <tr class="summary-subtotal">
                            <td>
                                <h4 class="summary-subtitle"> جمع (پس از تخفیف ها و مالیات):</h4>
                            </td>
                            <td>
                                <p class="summary-total-price"> {{ order.get_total_cost | commafy }} تومان </p>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <h2 class="title title-simple text-right pt-10 mb-2">اطلاعات</h2>
                <div class="address-info pb-8 mb-6">
                    <p class="address-detail pb-2">
                        {{ order.province }}<br>
                        {{ order.city }}<br>
                        {{ order.address }}<br>
                        {{ order.description }}<br>
                        برای {{ order.user }} با کد ملی {{ order.national_code }}
                    </p>
                    {% if order.email %}
                        <p class="email">{{ order.email }}</p>
                    {% endif %}
                </div>
                <a href="{% url 'shop:product-list' %}" class="btn btn-icon-right btn-dark btn-back btn-rounded btn-md mb-4 btn-checkout btn-gradient">
                    بازگشت به فروشگاه<i class="fa-light fa-angles-left"></i>
                </a>

                {% if order.status == 'NOT_PAID' %}
                    <hr>
                    <aside class="col-lg-4 sticky-sidebar-wrapper">
                        <div class="sticky-sidebar mt-1" data-sticky-options="{'bottom': 50}">
                            <div class="summary pt-5">
                                <h3 class="title title-simple">پرداخت</h3>
                                <div class="payment accordion radio-type">
                                    <h4 class="summary-subtitle ls-m pb-3">نحوه پرداخت </h4>
                                    <div class="card">
                                        <div class="card-header">
                                            <a href="#collapse1"
                                               class="collapse text-body text-normal ls-m">
                                                درگاه پرداخت
                                            </a>
                                        </div>
                                        <div id="collapse1" class="expanded payment-type" style="display: block;">
                                            <div class="card-body ls-m">
                                                به راحتی از طریق درگاه پرداخت امن زرین پال خرید خود را انجام دهید
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-header">
                                            <a href="#collapse2" class="expand text-body text-normal ls-m">
                                                با کارت هدیه
                                            </a>
                                        </div>
                                        <div id="collapse2" class="collapsed payment-type">
                                            <div class="card-body ls-m">
                                                <p id="response">در صورت که از وضعیت کارت هدیه خود اطمینان ندارید می توانید از بخش کارت هدیه وضعیت ان را برسی کنید</p>
                                                <input type="text" name="credit_token" class="input-text form-control text-grey ls-m" id="credit_token" value="{{ request.user.credit_cart.first.token }}" maxlength="10" placeholder="توکن خود را وارد کنید">
                                            </div>
                                        </div>
                                    </div>
                                    <button class="btn btn-md btn-block btn-gradient mt-3 {% if request.user.is_authenticated %}pay-order{% else %}login-toggle{% endif %}">
                                        پرداخت
                                    </button>
                                </div>
                            </div>
                        </div>
                    </aside>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

{% block script %}
    <script defer src="{% static 'js/order-status.js' %}"></script>
{% endblock %}

order/templates/verify.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
	احراز هویت
{% endblock %}

{% block page_keywords %}
    تأیید سفارش, تأیید اطلاعات, ثبت سفارش, فروشگاه نی عنبر, صفحه تأیید,
{% endblock %}

{% block page_description %}
    لطفاً اطلاعات خود را تأیید کنید تا سفارش شما در فروشگاه نی عنبر ثبت شود. فرآیند سریع و امن برای تکمیل خرید شما.
{% endblock %}

{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">احراز هویت</h1>
            <p class="page-desc text-white mb-0">
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}">خانه</a></li>
                    <li><a href="{% url 'cart:cart' %}">سبد خرید</a></li>
                    <li><a href="{% url 'order:order' %}">صورت حساب</a></li>
                    <li>ورود</li>
                </ul>
            </div>
        </nav>
        <div class="page-content">
            <div class="step-by pr-4 pl-4">
                <h3 class="title title-simple title-step"><a href="{% url 'cart:cart' %}">1. سبد خرید</a></h3>
                <h3 class="title title-simple title-step"><a>2. صورت حساب</a></h3>
                <h3 class="title title-simple title-step active"><a>3. احراز هویت</a></h3>
                <h3 class="title title-simple title-step"><a>4. تکمیل خرید</a></h3>
            </div>
            <div class="container section-bottom-margin">
                <div class="login-popup">
                    <div class="form-box">
                        <div class="container-fluid title-wrap">
                            <h2 class="title title-center mt-4 ">احراز هویت</h2>
                            <h5 class="title-info">
                                <span></span>
                                <picture><source srcset="{% static 'images/perfume/15.webp' %}" type="image/webp"><img src="{% static 'images/perfume/15.png' %}"></picture>
                                <span></span>
                            </h5>
                        </div>
                        <div id="signin">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group mb-4">
                                    <label>کد تایید <i class="fa-light fa-star-of-life"></i></label>
                                    <input type="number" class="form-control text-left" id="token" name="token"
                                           inputmode="numeric"
                                           oninput="this.value = this.value.replace(/[^0-9]/g, '');"
                                           placeholder="۱۲۳۴"
                                           required />
                                </div>
                                <button class="btn btn-md btn-block btn-gradient" type="submit">
                                    تایید
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}