Neyanbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tinymce/", include('tinymce.urls')),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('view_handler/', views.view_handler, name='view_handler'),
    path('comment/', views.comment_view, name='comment_view'),
    path('editor/upload/', views.editor_upload_handler, name='editor-upload'),
    path('posts/list/', views.post_list_view, name='post-list'),
    path('posts/detail/<slug>/', views.post_detail_view, name='post-detail'),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('credit-card/', views.credit_card_view, name='credit_card'),
    path('credit-card/create/', views.credit_card_create_view, name='credit_card_create'),
    path('credit-card/charge/<charge>/', views.credit_card_charge_view, name='credit_card_charge'),
    path('request/perfume/', views.perfume_request_view, name='perfume-request'),
    path('about-us/', views.about_us_view, name='about_us'),
    path('terms/', views.terms_view, name='terms'),
    # path('faq/', views.faq_view, name='faq'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('view_handler/', views.view_handler, name='view_handler'),
    path('like_handler/', views.like_handler, name='like_handler'),
    path('comment_handler/', views.comment_handler, name='comment_handler'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('notify_me/', views.notify_me, name='notify_me'),
    path('products/list/', views.product_list_view, name='product-list'),
    path('products/detail/<slug>/', views.product_view, name='product-detail'),
]

main/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from shop.models import Product, Brand


class Setting(models.Model):
    objects = models.Manager()

    site_access = models.BooleanField(default=True, verbose_name='دسترسی به سایت', help_text='دسترسی همه کاربران از سایت قطع می شود.')

    order_waiting_days = models.PositiveIntegerField(default=3, verbose_name='زودترین زمان ثبت سفارش', help_text='تعداد روز های مورد نیاز برای پردازش هر سفارش')
    orders_per_day = models.PositiveIntegerField(default=1, verbose_name='بیشترین تعداد سفارش در یک روز')
    order_days_limit = models.PositiveIntegerField(default=3, verbose_name='تعداد روز های قابل انتخاب برای دریافت سفارش')
    post_fee = models.PositiveIntegerField(default=10, validators=[MinValueValidator(10)], verbose_name='کرایه پست', help_text='به تومان')
    post_fee_max = models.PositiveIntegerField(default=1_000_000, validators=[MinValueValidator(10)], verbose_name='حداکثر هزینه اعمال پست', help_text='در صورتی که هزینه سفارش بیشتر از جداکثر بشه کرایه پست رایگان در نظر گرفته میشه')
    tax_fee = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(100)], verbose_name='مالیات', help_text='به درصد')

    show_offer = models.BooleanField(default=False, verbose_name='نمایش پیشنهاد')
    title = models.CharField(max_length=50, blank=True, verbose_name='تیتر پیشنهاد')
    event = models.CharField(max_length=100, blank=True, verbose_name='(مناسبت/علت تخفیف) پیشنهاد')
    products = models.CharField(blank=True, verbose_name='محصولات انتخاب شده', help_text='بر اساس لیست پیشنهاد های مجاز')
    banner = models.ImageField(upload_to='offers/', blank=True, verbose_name='بنر')

    video_text = models.CharField(max_length=150, blank=True, verbose_name='متن ویدیو')
    footer_text = models.TextField(blank=True, verbose_name='متن فوتر')

    def get_post_fee(self, order_total):
        return self.post_fee if order_total < self.post_fee_max else 0

    def get_offer_link(self):
        if not self.show_offer or not self.products:
            return ''
        args = self.products.split(':')[1]
        if self.products.startswith('products:'):
            if not ';' in args:
                return reverse('shop:product-detail', kwargs={'slug': args})
            return reverse('shop:product-list') + f'?products={args}'
        elif self.products.startswith('brands:'):
            return reverse('shop:product-list') + f'?brands={args}'
        elif self.products.startswith('volumes:'):
            return reverse('shop:product-list') + f'?volumes={args}'
        elif self.products.startswith('smells'):
            return reverse('shop:product-list') + f'?smells={args}'
        elif self.products.startswith('spreads'):
            return reverse('shop:product-list') + f'?spreads={args}'
        elif self.products.startswith('seasons:'):
            return reverse('shop:product-list') + f'?seasons={args}'
        elif self.products.startswith('tastes:'):
            return reverse('shop:product-list') + f'?tastes={args}'
        elif self.products.startswith('nature'):
            return reverse('shop:product-list') + f'?nature={args}'
        elif self.products.startswith('durability:'):
            return reverse('shop:product-list') + f'?durability={args}'
        elif self.products.startswith('gender'):
            return reverse('shop:product-list') + f'?gender={args}'
        elif self.products.startswith('type:'):
            return reverse('shop:product-list') + f'?type={args}'
        return ''

    def get_offer_products(self):
        if not self.show_offer or not self.products:
            return []
        args = self.products.split(':')[1].split(';')
        if self.products.startswith('products:'):
            return Product.objects.filter(slug__in=args)
        elif self.products.startswith('brands:'):
            return Product.objects.filter(brand__slug__in=args)
        elif self.products.startswith('volumes:'):
            return Product.objects.filter(available_volumes__volume__in=args)
        elif self.products.startswith('smells'):
            return Product.objects.filter(smell__value__in=args)
        elif self.products.startswith('spread'):
            return Product.objects.filter(spread__in=args)
        elif self.products.startswith('seasons:'):
            return Product.objects.filter(season__in=args)
        elif self.products.startswith('tastes:'):
            return Product.objects.filter(taste__in=args)
        elif self.products.startswith('nature'):
            return Product.objects.filter(nature__in=args)
        elif self.products.startswith('durability:'):
            return Product.objects.filter(durability__in=args)
        elif self.products.startswith('gender'):
            return Product.objects.filter(gender__in=args)
        elif self.products.startswith('type:'):
            return Product.objects.filter(type__in=args)
        return []

    def __str__(self):
        return 'تنظیمات'

    class Meta:
        verbose_name = verbose_name_plural = 'تنظیمات'


class PerfumeRequest(models.Model):
    objects = models.Manager()
    text = models.EmailField(max_length=255, unique=True, verbose_name='متن درخواست')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'درخواست عطر'
        verbose_name_plural = 'درخواست عطر'


class FAQ(models.Model):
    objects = models.Manager()
    question = models.CharField(max_length=255, verbose_name='سوال')
    answer = models.TextField(verbose_name='جواب')
    is_visible = models.BooleanField(default=True, verbose_name='نمایش در سایت')
    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'سوال متداول'
        verbose_name_plural = 'سوالات متداول'


class AboutUs(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=255, verbose_name='تیتر')
    description = models.TextField(verbose_name='توضیحات')
    image = models.ImageField(upload_to='about_us', verbose_name='تصویر')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'درباره ما'
        verbose_name_plural = 'درباره ما'


class Terms(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=255, verbose_name='تیتر')
    description = models.TextField(verbose_name='توضیحات')
    image = models.ImageField(upload_to='terms', verbose_name='تصویر')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'شرایط و ضوابط'
        verbose_name_plural = 'شرایط و ضوابط'

main/views.py
from django.db.models import Count, Min, Max, ExpressionWrapper, Case, When, F, IntegerField
from django.shortcuts import render, redirect
from blog.models import Post
from shop.models import Product, Brand
from .models import Setting, AboutUs, Terms, PerfumeRequest
from order.models import CreditCart
from uuid import uuid4
from order.zarinpal import start_payment
from jdatetime import date as jdate


def home_view(request):
    all_products = Product.objects.select_related('brand').filter(is_visible=True).annotate(
        verified_comments_count=Count('comments')
    )
    all_brands = Brand.objects.filter(products__is_visible=True).annotate(
        max_discount=Max('products__discount'),
        min_price=Min('products__price'),
        min_discount=Min('products__discount'),
        min_volume=Min('products__available_volumes__volume'),
        least_price=ExpressionWrapper(
            Case(
                When(max_discount=-1, then=F('min_price')),
                default=F('min_discount'),
                output_field=IntegerField()
            ) * F('min_volume'),
            output_field=IntegerField()
        )
    ).order_by('-products__site_score').distinct()[:4]

    title_products = all_products.filter(discount__gt=-1)
    if not title_products.exists():
        title_products = all_products.order_by('-views')

    settings = Setting.objects.first()
    title_product = title_products[0]

    top_discounts = title_products.exclude(id=title_product.id).annotate(max_discount=Max('discount')).order_by('-max_discount')[:6]

    tastes = {
        'sweet_product': Product.TasteChoices.SWEET,
        'sour_product': Product.TasteChoices.SOUR,
        'bitter_product': Product.TasteChoices.BITTER,
        'spicy_product': Product.TasteChoices.SPICY,
    }
    taste_products = {
        key: all_products.filter(taste=value).order_by('-site_score').first()
        for key, value in tastes.items()
    }

    def get_top_gender_product(genders):
        return all_products.filter(gender__in=genders).annotate(
            max_discount=Max('discount'),
            min_discount=Min('discount'),
            min_price=Min('price'),
            min_volume=Min('available_volumes__volume'),
            least_price=ExpressionWrapper(
                Case(
                    When(max_discount=-1, then=F('min_price')),
                    default=F('min_discount'),
                    output_field=IntegerField()
                ) * F('min_volume'),
                output_field=IntegerField()
            )
        ).order_by('least_price').first()

    top_male_product = get_top_gender_product([Product.GenderChoices.MALE, Product.GenderChoices.UNISEX])
    top_female_product = get_top_gender_product([Product.GenderChoices.FEMALE, Product.GenderChoices.UNISEX])

    new_products = all_products.order_by('-created_at')[:7]
    high_rated_products = all_products.order_by('-site_score')[:7]
    most_sold_products = all_products.annotate(sold=Count('bought_by', distinct=True)).order_by('-sold')[:7]
    most_viewed_products = all_products.order_by('-views')[:7]

    context = {
        'posts': Post.objects.select_related('user').filter(is_visible=True).order_by('-created_at')[:6],
        'title_product': title_product,
        'top_brands': all_brands,
        'neyanbar_suggestion': all_products.order_by('-views')[:6],
        'top_discounts': top_discounts,
        **taste_products,
        'top_male_product': top_male_product,
        'top_female_product': top_female_product,
        'new_products': new_products,
        'high_rated_products': high_rated_products,
        'most_sold_products': most_sold_products,
        'most_viewed_products': most_viewed_products,
        'video_text': settings.video_text,
        'footer_text': settings.footer_text,
    }
    if settings.show_offer:
        context.update({
            'offer_title': settings.title,
            'offer_event': settings.event,
            'offer_link': settings.get_offer_link(),
            'offer_banner': settings.banner.url,
        })
    if jdate.today().month <= 6:
        context.update({
            'season_title': 'عطر های بهاری و تابستانی',
            'season_products': all_products.filter(season__in=[Product.SeasonChoices.SUMMER, Product.SeasonChoices.ALL_SEASONS]).order_by('-discount')[:7]
        })
    else:
        context.update({
            'season_title': 'عطر های پاییزی و زمستانی',
            'season_products': all_products.filter(season__in=[Product.SeasonChoices.WINTER, Product.SeasonChoices.ALL_SEASONS]).order_by('-discount')[:7]
        })
    return render(request, 'index.html', context)


def credit_card_view(request):
    if not request.user.is_authenticated:
        return render(request, 'credit-card-empty.html')
    credit_cart = None

    try:
        credit_cart = CreditCart.objects.filter(created_by=request.user)
        if not credit_cart.exists():
            return render(request, 'credit-card-empty.html')
        return render(request, 'credit-card.html', {'credit_carts': credit_cart})
    except CreditCart.DoesNotExist:
        return render(request, 'credit-card-empty.html')


def credit_card_create_view(request):
    if not request.user.is_authenticated or CreditCart.objects.filter(created_by=request.user).exists():
        return redirect('main:credit_card')

    CreditCart.objects.create(
        token=str(uuid4())[:10],
        credit=0,
        created_by=request.user,
    )

    return redirect('main:credit_card')


def credit_card_charge_view(request, charge):
    if not request.user.is_authenticated:
        return redirect('main:credit_card')
    credit_card = None
    try:
        credit_card = CreditCart.objects.get(created_by=request.user)
        if charge in ('100000', '250000', '500000', '750000', '1000000', '5000000', '10000000', '15000000', '20000000'):
            print('*' * 30)
            print('REDIRECTED TO GATEWAY PAGE')
            print('*' * 30)
            return start_payment(request, credit_card.pk, False, charge)
    except CreditCart.DoesNotExist:
        return redirect(request, 'credit-card-empty.html')

    return redirect('main:credit_card')


def perfume_request_view(request):
    p_request = request.GET.get('request')
    if p_request:
        PerfumeRequest.objects.get_or_create(text=p_request)
    return redirect('main:index')


def about_us_view(request):
    return render(request, 'about-us.html', {'objects': AboutUs.objects.all(), 'show_info': True, 'title': 'درباره ما'})


def terms_view(request):
    return render(request, 'about-us.html', {'objects': Terms.objects.all(), 'show_info': False, 'title': 'شرایط و ضوابط'})


# def faq_view(request):
#     return render(request, 'faq.html', {'faq': FAQ.objects.filter(is_visible=True)})

main/templates/about-us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	درباره ما
{% endblock %}

{% block title_og %}
	درباره ما
{% endblock %}

{% block page_keywords %}
    درباره ما, فروشگاه نی عنبر, عطر طبیعی, عطر اسلامی, عطر دست‌ساز, عطر ایرانی, عطر با کیفیت, رایحه اصیل, عطرهای نیش, برند نی عنبر, عطرهای لوکس, فروشگاه عطر آنلاین,
{% endblock %}

{% block page_description %}
    فروشگاه نی عنبر، پیشرو در عرضه عطرهای طبیعی و اسلامی با رایحه‌های اصیل و دست‌ساز. با ما در دنیای عطرها همراه شوید و داستان هر رایحه را کشف کنید.
{% endblock %}


{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">{{ title }}</h1>
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}"><i class="fa-light fa-house"></i></a></li>
                    <li>{{ title }}</li>
                </ul>
            </div>
        </nav>
        <div class="page-content">
            {% if show_info %}
                <section class="about-section pb-10 appear-animate">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-lg-12 ">
                                <div class="row">
                                    <div class="col-md-12 mb-4">
                                        <div class="counter text-center text-dark">
                                            <span class="count-to" data-fromvalue="0" data-tovalue="150"
                                                  data-duration="900" data-delimiter=",">0</span>
                                            <h5 class="count-title">انواع رایحه های مدرن و کلاسیک</h5>
                                            <p class="text-grey mb-0">
                                                در خدمت شما هستیم<br>
                                                وازاینکه ما را انتخاب کردید متشکریم .
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}
            {% for object in objects %}
                {% cycle True False as is_odd %}
                {% if is_odd %}
                    <section class="customer-section appear-animate">
                        <div class="container customer-wrap">
                            <div class="row align-items-center">
                                <div class="col-md-7 mb-4 ">
                                    <figure>
                                        <picture>
                                            <source srcset="{{ object.image.url }}" type="image/webp">
                                            <img loading="lazy" decoding="async" src="{{ object.image.url }}" alt="Happy Customer" width="580"  height="507" class="banner-radius" style="background-color: #BDD0DE;" />
                                        </picture>
                                    </figure>
                                </div>
                                <div class="col-md-5 mb-4  text-right">
                                    <div class="container-fluid title-right-wrap">
                                        <h2 class="title-right">{{ object.title }}</h2>
                                        <h5 class="title-info-right">
                                            <span></span>
                                            <picture><source srcset="/static/images/perfume/15.webp" type="image/webp"><img src="/static/images/perfume/15.webp"></picture>
                                            <span></span>
                                        </h5>
                                    </div>
                                    <p class="section-desc text-grey">
                                        {{ object.description }}
                                    </p>
                                    <a href="{% url 'shop:product-list' %}" class="btn btn-dark btn-link btn-underline ls-m">
                                        از فروشگاه ما دیدن کنید <i class="fa-light fa-angles-left"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </section>
                {% else %}
                    <section class="store-section pb-10 appear-animate">
                        <div class="container store-wrap">
                            <div class="row align-items-center ">
                                <div class="col-md-6 order-md-first mb-4 text-right">
                                    <div class="container-fluid title-right-wrap">
                                        <h2 class="title-right">{{ object.title }}</h2>
                                        <h5 class="title-info-right">
                                            <span></span>
                                            <picture><source srcset="/static/images/perfume/15.webp" type="image/webp"><img src="/static/images/perfume/15.png"></picture>
                                            <span></span>
                                        </h5>
                                    </div>
                                    <p class="section-desc text-grey">
                                        {{ object.description }}
                                    </p>
                                    <a href="{% url 'main:index' %}" class="btn btn-dark btn-link btn-underline ls-m">
                                        از فروشگاه  ما دیدن کنید <i class="fa-light fa-angles-left"></i>
                                    </a>
                                </div>
                                <div class="col-md-6 mb-4 store-img">
                                    <figure>
                                        <picture>
                                            <source srcset="{{ object.image.url }}" type="image/webp">
                                            <img loading="lazy" decoding="async" src="{{ object.image.url }}" alt="Our Store" width="580" height="507" class="banner-radius" style="background-color: #DEE6E8;" />
                                        </picture>
                                    </figure>
                                </div>
                            </div>
                        </div>
                    </section>
                {% endif %} 	
            {% endfor %}
        </div>
    </main>
{% endblock %}

{% block script %}
    <script defer src="{% static 'plugin/jquery.count-to/jquery-numerator.min.js' %}"></script>
{% endblock %}

main/templates/credit-card-empty.html
{% extends 'base.html' %}

{% block title %}
	کارت هدیه
{% endblock %}

{% block title_og %}
	کارت هدیه
{% endblock %}

{% block page_keywords %}
    کارت هدیه, هدیه عطر, کارت هدیه نی عنبر, خرید کارت هدیه, هدیه خاص, کارت هدیه آنلاین, فروشگاه نی عنبر, عطر هدیه, خرید هدیه عطر, کارت هدیه دیجیتال,
{% endblock %}

{% block page_description %}
    کارت هدیه نی عنبر، بهترین انتخاب برای هدیه دادن عطرهای خاص و طبیعی. با خرید کارت هدیه، به عزیزانتان امکان انتخاب رایحه دلخواه را هدیه دهید.
{% endblock %}

{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">کارت اعتباری</h1>
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}"><i class="fa-light fa-house"></i></a></li>
                    <li>لیست کارت های هدیه</li>
                </ul>
            </div>
        </nav>
        <div class="page-content wishlist-empty">
            <div class="container">
                <div class="main-content">
                    <i class="fa-light fa-heart wishlist-icon"></i>
                    {% if request.user.is_authenticated %}
                        <h2 class="wishlist-description">شما هیچ کارت هدیه ای ندارید</h2>
                        <a class="btn btn-primary btn-rounded" href="{% url 'main:credit_card_create' %}">ساختن کارت هدیه</a>
                    {% else %}
                        <h2 class="wishlist-description">برای ساخت کارت هدیه ابتدا وارد حساب کاربری خود شوید</h2>
                        <a class="btn btn-primary btn-rounded login-toggle">ورود به حساب کاربری</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

main/templates/credit-card.html
{% extends 'base.html' %}
{% load tags %}

{% block title %}
	کارت هدیه
{% endblock %}

{% block title_og %}
	کارت هدیه
{% endblock %}

{% block page_keywords %}
    کارت هدیه, هدیه عطر, کارت هدیه نی عنبر, خرید کارت هدیه, هدیه خاص, کارت هدیه آنلاین, فروشگاه نی عنبر, عطر هدیه, خرید هدیه عطر, کارت هدیه دیجیتال,
{% endblock %}

{% block page_description %}
    کارت هدیه نی عنبر، بهترین انتخاب برای هدیه دادن عطرهای خاص و طبیعی. با خرید کارت هدیه، به عزیزانتان امکان انتخاب رایحه دلخواه را هدیه دهید.
{% endblock %}


{% block content %}
    <main class="main rtl text-right">
        <div class="page-header pl-4 pr-4">
            <h3 class="page-subtitle font-weight-bold">خوش آمدید به وبسایت ما</h3>
            <h1 class="page-title font-weight-bold lh-1 text-white">کارت هدیه</h1>
            <p class="page-desc text-white mb-0">برای ارسال کارت هدیه به دیگران از توکن استفاده کنید</p>
            <p class="page-desc text-white mb-0">با استفاده از توکن کارت هدیه(کارت اعتباری) می توانید خرید های خود را انجام دهید</p>
        </div>
        <nav class="breadcrumb-nav">
            <div class="container breadcrumb-nav-wrap">
                <ul class="breadcrumb ">
                    <li><a href="{% url 'main:index' %}"><i class="fa-light fa-house"></i></a></li>
                    <li>لیست علاقه مندی</li>
                </ul>
            </div>
        </nav>
        <div class="page-content">
            <div class="container wishlist-wrap">
                <table class="shop-table wishlist-table mt-2 mb-4">
                    <thead>
                    <tr>
                        <th class="product-name"><span>توکن</span></th>
                        <th></th>
                        <th class="product-price"><span>باقیمانده</span></th>
                        <th class="product-stock-status"><span>شارژ</span></th>
                        <th class="product-add-to-cart"></th>
                        <th class="product-remove"></th>
                    </tr>
                    </thead>
                    <tbody class="wishlist-items-wrapper">
                    {% for credit_cart in credit_carts %}
                        <tr>
                            <td class="product-thumbnail">
                                <a>{{ credit_cart.token }}</a>
                            </td>
                            <td class="product-name">
                            </td>
                            <td class="product-price">
                                <span class="amount"> {{ credit_cart.credit | commafy }} تومان </span>
                            </td>
                            <td class="product-stock-status">
                                <select class="form-control" name="amount-select" id="amount-select">
                                    <option value="100000" selected>{{ 100000 | commafy }} تومان</option>
                                    <option value="250000">{{ 250000 | commafy }} تومان</option>
                                    <option value="500000">{{ 500000 | commafy }} تومان</option>
                                    <option value="750000">{{ 750000 | commafy }} تومان</option>
                                    <option value="1000000">{{ 1000000 | commafy }} تومان</option>
                                    <option value="2000000">{{ 2000000 | commafy }} تومان</option>
                                    <option value="5000000">{{ 5000000 | commafy }} تومان</option>
                                    <option value="10000000">{{ 10000000 | commafy }} تومان</option>
                                    <option value="15000000">{{ 15000000 | commafy }} تومان</option>
                                    <option value="20000000">{{ 20000000 | commafy }} تومان</option>
                                </select>
                            </td>
                            <td class="product-add-to-cart">
                                <button class="btn-product btn-primary btn-charge"><span>اعمال شارژ</span></button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{% endblock %}

{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const btnCharge = document.querySelector('.btn-charge');
            if (btnCharge) {
                btnCharge.addEventListener('click', function(e) {
                    const amountSelect = document.getElementById('amount-select');
                    const charge = amountSelect ? amountSelect.value : '';
                    if (charge) {
                        location.href = `/credit-card/charge/${charge}`;
                    }
                });
            }
        });
    </script>
{% endblock %}
        